org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=extrasounds
mod.name=ExtraSounds Next
mod.group=dev.arbor
mod.version=1.5.1
mod.channel_tag=
mod.authors=Arborsm, stashymane
mod.contributors=
mod.license=MIT
mod.description=Improve your clicks, scrolls and more with Extra Sounds.
mod.sources_url=https://github.com/Arborsm/ExtraSoundsNext
mod.homepage_url=https://github.com/Arborsm/ExtraSoundsNext
mod.issues_url=https://github.com/Arborsm/ExtraSoundsNext/issues
mod.discord_url=

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.jei=[VERSIONED]
deps.rei=[VERSIONED]
deps.emi=[VERSIONED]

publish.modrinth=jv7tzVE4
publish.curseforge=946784
publish.github=true
