[versions]
stonecutter = "0.9-alpha.3"
	stonecutter-postprocess = "2.1-beta.8"
mod-publish = "1.1.0"
dotenv-gradle = "4.0.0"
fabric-loom = "1.14-SNAPSHOT"
neoforge-moddev = "2.0.120"
foojay = "1.0.0"
fabric-loader = "0.17.3"
devtools-ksp = "2.2.10-2.0.2"
kotlin-jvm = "2.2.10"
fletching-table = "0.1.0-alpha.22"
moulberry-mixinconstraints = "1.1.0"
vanniktech-maven-publish = "0.35.0"
mixin = "0.8.5"
mixinextras = "0.3.5"

[libraries]
kikugie-postprocess = { module = "dev.kikugie:postprocess", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
fletching-table = { module = "dev.kikugie:fletching-table", version.ref = "fletching-table" }
moulberry-mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "moulberry-mixinconstraints" }
mixinextras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv-gradle" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
jsonlang-postprocess = { id = "dev.kikugie.postprocess.jsonlang", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
fletching-table = { id = "dev.kikugie.fletching-table", version.ref = "fletching-table" }
legacyforge-moddev = { id = "net.neoforged.moddev.legacyforge", version.ref = "neoforge-moddev" }
